FROM python:3.11-slim

WORKDIR /app

# Copy only requirements file
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Don't copy the code here - we'll use volumes instead

EXPOSE 5050

# Make sure to use python -m flask to run the app
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5050"]